## Language Identifier
<br>
<b>Problem:</b> Is it possible to identify a text language using only 2 features?
<br>

<b>Input:</b> " Any Text"
<br>
<b>Output:</b> Português ou Inglês ou Espanhol

In [2]:
#
# Different Language Samples
#

ingles = [
"Hello, how are you?",
"I love to read books.",
"The weather is nice today.",
"Where is the nearest restaurant?",
"What time is it?",
"I enjoy playing soccer.",
"Can you help me with this?",
"I'm going to the movies tonight.",
"This is a beautiful place.",
"I like listening to music.",
"Do you speak English?",
"What is your favorite color?",
"I'm learning to play the guitar.",
"Have a great day!",
"I need to buy some groceries.",
"Let's go for a walk.",
"How was your weekend?",
"I'm excited for the concert.",
"Could you pass me the salt, please?",
"I have a meeting at 2 PM.",
"I'm planning a vacation.",
"She sings beautifully.",
"The cat is sleeping.",
"I want to learn French.",
"I enjoy going to the beach.",
"Where can I find a taxi?",
"I'm sorry for the inconvenience.",
"I'm studying for my exams.",
"I like to cook dinner at home.",
"Do you have any recommendations for restaurants?",
]

espanhol = [
"Hola, ¿cómo estás?",
"Me encanta leer libros.",
"El clima está agradable hoy.",
"¿Dónde está el restaurante más cercano?",
"¿Qué hora es?",
"Voy al parque todos los días.",
"¿Puedes ayudarme con esto?",
"Me gustaría ir de vacaciones.",
"Este es mi libro favorito.",
"Me gusta bailar salsa.",
"¿Hablas español?",
"¿Cuál es tu comida favorita?",
"Estoy aprendiendo a tocar el piano.",
"¡Que tengas un buen día!",
"Necesito comprar algunas frutas.",
"Vamos a dar un paseo.",
"¿Cómo estuvo tu fin de semana?",
"Estoy emocionado por el concierto.",
"¿Me pasas la sal, por favor?",
"Tengo una reunión a las 2 PM.",
"Estoy planeando unas vacaciones.",
"Ella canta hermosamente.",
"El perro está jugando.",
"Quiero aprender italiano.",
"Disfruto ir a la playa.",
"¿Dónde puedo encontrar un taxi?",
"Lamento las molestias.",
"Estoy estudiando para mis exámenes.",
"Me gusta cocinar la cena en casa.",
"¿Tienes alguna recomendación de restaurantes?",
]

portugues = [
"Estou indo para o trabalho agora.",
"Adoro passar tempo com minha família.",
"Preciso comprar leite e pão.",
"Vamos ao cinema no sábado.",
"Gosto de praticar esportes ao ar livre.",
"O trânsito está terrível hoje.",
"A comida estava deliciosa!",
"Você já visitou o Rio de Janeiro?",
"Tenho uma reunião importante amanhã.",
"A festa começa às 20h.",
"Estou cansado depois de um longo dia de trabalho.",
"Vamos fazer um churrasco no final de semana.",
"O livro que estou lendo é muito interessante.",
"Estou aprendendo a cozinhar pratos novos.",
"Preciso fazer exercícios físicos regularmente.",
"Vou viajar para o exterior nas férias.",
"Você gosta de dançar?",
"Hoje é meu aniversário!",
"Gosto de ouvir música clássica.",
"Estou estudando para o vestibular.",
"Meu time de futebol favorito ganhou o jogo.",
"Quero aprender a tocar violão.",
"Vamos fazer uma viagem de carro.",
"O parque fica cheio aos finais de semana.",
"O filme que assisti ontem foi ótimo.",
"Preciso resolver esse problema o mais rápido possível.",
"Adoro explorar novos lugares.",
"Vou visitar meus avós no domingo.",
"Estou ansioso para as férias de verão.",
"Gosto de fazer caminhadas na natureza.",
"O restaurante tem uma vista incrível.",
"Vamos sair para jantar no sábado.",
]

In [3]:
import random

pre_padroes = []
for frase in ingles:
    pre_padroes.append( [frase, 'inglês'])

for frase in espanhol:
    pre_padroes.append( [frase, 'espanhol'])

for frase in portugues:
    pre_padroes.append( [frase, 'português'])

random.shuffle(pre_padroes)
print(pre_padroes)

[['I like to cook dinner at home.', 'inglês'], ['Tenho uma reunião importante amanhã.', 'português'], ['El perro está jugando.', 'espanhol'], ['Vamos sair para jantar no sábado.', 'português'], ['Estou estudando para o vestibular.', 'português'], ['Gosto de fazer caminhadas na natureza.', 'português'], ['Where is the nearest restaurant?', 'inglês'], ['What is your favorite color?', 'inglês'], ['Vamos fazer um churrasco no final de semana.', 'português'], ['The cat is sleeping.', 'inglês'], ['Vou visitar meus avós no domingo.', 'português'], ['Do you have any recommendations for restaurants?', 'inglês'], ['Estou cansado depois de um longo dia de trabalho.', 'português'], ['I want to learn French.', 'inglês'], ['Adoro explorar novos lugares.', 'português'], ['I love to read books.', 'inglês'], ['O restaurante tem uma vista incrível.', 'português'], ['¿Qué hora es?', 'espanhol'], ['Estou aprendendo a cozinhar pratos novos.', 'português'], ['Você gosta de dançar?', 'português'], ['How was 

In [4]:
import pandas as pd

dados = pd.DataFrame(pre_padroes)

dados = dados.rename(columns={0:'frase',1:'label'})

dados

frase      label
0                  I like to cook dinner at home.     inglês
1            Tenho uma reunião importante amanhã.  português
2                          El perro está jugando.   espanhol
3               Vamos sair para jantar no sábado.  português
4              Estou estudando para o vestibular.  português
..                                            ...        ...
87  ¿Tienes alguna recomendación de restaurantes?   espanhol
88                     The weather is nice today.     inglês
89        ¿Dónde está el restaurante más cercano?   espanhol
90                 ¿Cómo estuvo tu fin de semana?   espanhol
91                       Ella canta hermosamente.   espanhol

[92 rows x 2 columns]

<h1>Construção dos atributos</h1>
<p>Esse é o coração desse trabalho e que deverá ser desenvolvido por vocês. Pensem em como podemos "medir" cadas frase/sentença e extrair características que melhorem o resultado do processo de identificação.<p>
<p>Após a criação de cada novo atributo, execute as etapas seguintes e registre as métricas da matriz de confusão. Principalmente acurácia e a precisão.</p>

In [5]:
import re
from unidecode import unidecode

# Evaluates the average sentence length
def tamanhoMedioFrases(texto):
    palavras = re.split("\s",texto)
    tamanhos = [len(s) for s in palavras if len(s)>0]
    soma = 0
    for t in tamanhos:
        soma=soma+t
    return soma / len(tamanhos)

# Evaluates the frequency of each letter on a phrase
def avaliar_frequencia_letras(texto_raw):

    # "Empty" - Zero Default Dictionary
    dict_alf = {'a':0,'b':0,'c':0,'d':0,'e':0,'f':0,'g':0,'h':0,'i':0,'j':0,'k':0,'l':0,'m':0,'n':0,'o':0,'p':0,'q':0,'r':0,'s':0,'t':0,'u':0,'v':0,'w':0,'x':0,'y':0,'z':0}
    
    # Text standardization 
    texto_limpo = unidecode(texto_raw.lower().replace(' ',''))

    # Count the frequency of each letter
    dicionario_contagem = {chave_letra: texto_limpo.count(chave_letra) for chave_letra in dict_alf.keys()}

    return list(dicionario_contagem.values())



def extraiCaracteristicas(frase):
  # Sentence as a vector [ 'text', 'language' ]
    texto_raw = frase[0]
    texto = frase[0]

    pattern_regex = re.compile('[^\w+]', re.UNICODE)
    texto = re.sub(pattern_regex,' ',texto)

  # Features generation
    caracteristica1 = tamanhoMedioFrases(texto)
    caracteristica2 = avaliar_frequencia_letras(texto_raw)

  # List generation
    padrao = caracteristica2
    padrao.append(caracteristica1)
    padrao.append(frase[1])
    
    return padrao


def geraPadroes(frases):
    padroes = []
    
    for frase in frases:
        padrao = extraiCaracteristicas(frase)
        padroes.append(padrao)
        
    return padroes


padroes = geraPadroes(pre_padroes)
print(padroes)

dados = pd.DataFrame(padroes)

dados

[[1, 0, 1, 1, 3, 0, 0, 1, 3, 0, 2, 1, 1, 2, 4, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 3.2857142857142856, 'inglês'], [6, 0, 0, 0, 3, 0, 0, 2, 2, 0, 0, 0, 3, 4, 3, 1, 0, 2, 0, 3, 2, 0, 0, 0, 0, 0, 6.2, 'português'], [2, 0, 0, 1, 3, 0, 1, 0, 0, 1, 0, 1, 0, 1, 2, 1, 0, 2, 1, 1, 1, 0, 0, 0, 0, 0, 4.5, 'espanhol'], [8, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 2, 3, 1, 0, 3, 3, 1, 0, 1, 0, 0, 0, 0, 4.5, 'português'], [4, 1, 0, 2, 3, 0, 0, 0, 1, 0, 0, 1, 0, 1, 3, 1, 0, 2, 3, 3, 3, 1, 0, 0, 0, 0, 5.8, 'português'], [7, 0, 1, 2, 3, 1, 1, 1, 1, 0, 0, 0, 1, 3, 2, 0, 0, 2, 2, 2, 1, 0, 0, 0, 0, 2, 5.333333333333333, 'português'], [3, 0, 0, 0, 6, 0, 0, 2, 1, 0, 0, 0, 0, 2, 0, 0, 0, 4, 3, 4, 1, 0, 1, 0, 0, 0, 5.4, 'inglês'], [2, 0, 1, 0, 1, 1, 0, 1, 2, 0, 0, 1, 0, 0, 4, 0, 0, 3, 1, 2, 1, 1, 1, 0, 1, 0, 4.6, 'inglês'], [6, 0, 2, 1, 3, 2, 0, 1, 1, 0, 0, 1, 3, 3, 3, 0, 0, 3, 3, 0, 2, 1, 0, 0, 0, 1, 4.5, 'português'], [1, 0, 1, 0, 3, 0, 1, 1, 2, 0, 0, 1, 0, 1, 0, 1, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 4.0, 'inglês'], [2,

0   1   2   3   4   5   6   7   8   9   ...  18  19  20  21  22  23  24  \
0    1   0   1   1   3   0   0   1   3   0  ...   0   2   0   0   0   0   0   
1    6   0   0   0   3   0   0   2   2   0  ...   0   3   2   0   0   0   0   
2    2   0   0   1   3   0   1   0   0   1  ...   1   1   1   0   0   0   0   
3    8   1   0   1   0   0   0   0   1   1  ...   3   1   0   1   0   0   0   
4    4   1   0   2   3   0   0   0   1   0  ...   3   3   3   1   0   0   0   
..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
87   5   0   2   2   7   0   1   0   2   0  ...   3   3   2   0   0   0   0   
88   2   0   1   1   4   0   0   2   2   0  ...   1   3   0   0   1   0   1   
89   5   0   2   2   6   0   0   0   0   0  ...   3   3   1   0   0   0   0   
90   2   0   1   1   3   1   0   0   1   0  ...   2   2   2   1   0   0   0   
91   4   0   1   0   4   0   0   1   0   0  ...   1   2   0   0   0   0   0   

    25        26         27  
0    0  3.285714     inglês  
1    0  6.200000  português  
2    0  4.500000   espanhol  
3    0  4.500000  português  
4    0  5.800000  português  
..  ..       ...        ...  
87   0  7.800000   espanhol  
88   0  4.200000     inglês  
89   0  5.333333   espanhol  
90   0  3.833333   espanhol  
91   0  7.000000   espanhol  

[92 rows x 28 columns]

<h2> SVM Model Training </h1>

In [16]:
from sklearn.model_selection import train_test_split
import numpy as np


#from sklearn.metrics import confusion_matrix

vet = np.array(padroes)
classes = vet[:,-1]         # classes = [p[-1] for p in padroes]

#print(classes)
padroes_sem_classe = vet[:,0:-1]

#print(padroes_sem_classe)
X_train, X_test, y_train, y_test = train_test_split(padroes_sem_classe, 
                                                    classes, 
                                                    test_size=0.15, 
                                                    random_state = 42,
                                                    stratify=classes)

In [22]:
from sklearn import svm
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

treinador = svm.SVC()
modelo = treinador.fit(X_train, y_train)

acuracia = modelo.score(X_train, y_train)
print("Accuracy on Training Set: {:.2f}%".format(acuracia * 100))

y_pred = modelo.predict(X_train)
cm = confusion_matrix(y_train, y_pred)
print(cm)
print(classification_report(y_train, y_pred))

print('Test Score Metric')
y_pred2 = modelo.predict(X_test)
cm = confusion_matrix(y_test, y_pred2)
print(cm)
print(classification_report(y_test, y_pred2))

Accuracy on Training Set: 89.74%
[[20  3  2]
 [ 1 24  1]
 [ 1  0 26]]
              precision    recall  f1-score   support

    espanhol       0.91      0.80      0.85        25
      inglês       0.89      0.92      0.91        26
   português       0.90      0.96      0.93        27

    accuracy                           0.90        78
   macro avg       0.90      0.90      0.90        78
weighted avg       0.90      0.90      0.90        78

Test Score Metric
[[5 0 0]
 [0 4 0]
 [1 0 4]]
              precision    recall  f1-score   support

    espanhol       0.83      1.00      0.91         5
      inglês       1.00      1.00      1.00         4
   português       1.00      0.80      0.89         5

    accuracy                           0.93        14
   macro avg       0.94      0.93      0.93        14
weighted avg       0.94      0.93      0.93        14

